### ISSUE TITLE
Tokenizer outputs single characters per line

### ISSUE THREAD

**Issue by konstantinmiller** [tsproisl/SoMaJo#13]
Thank you for proving this tool!

I might be doing something wrong but the following code produces an output with every character on its own line. So, basically, each identified token is just one character.

When calling `somajo-tokenizer` from the command line, it works as expected.

```
from somajo import SoMaJo
tokenizer = SoMaJo("de_CMC")
sentences = tokenizer.tokenize_text('Das ist ein Test.')
for sentence in sentences:
    for token in sentence:
        print(token.text)
```

**Comment by konstantinmiller** [comment]
While this works:

```
from somajo import SoMaJo
import io
tokenizer = SoMaJo("de_CMC")
sentences = tokenizer.tokenize_text_file(io.StringIO('Dies ist ein Text.'), SoMaJo._default_parsep)
for sentence in sentences:
    for token in sentence:
        print(token.text)
```

**Comment by peteruhrig** [comment]
Yes, the behaviour appears a bit odd. The reason is that the tokenize_text function expects a list of paragraphs. So you will have to write
`sentences = tokenizer.tokenize_text(['Das ist ein Test.'])`
instead.

**Comment by konstantinmiller** [comment]
Ah, got it! Thanks!

**Comment by tsproisl** [comment]
To make the intended usage more clear, `tokenize_text` raises an exception now if it is called with a string instead of an iterable of strings.
