### ISSUE TITLE
Apostrophe die Vokale ersetzen

### ISSUE THREAD

**Issue by anonymous-poetrybot-386** [tsproisl/SoMaJo#16]
Hi, 

Ich arbeite an (historischer) Lyrik, und da werden Apostrophe gerne verwendet um Vokale zu ersetzen (um eine Silbe zu sparen).

Beispiele: 

```
wär'
hingegeb'nen 
ward's
Bring's
Von Mutter-Lieb', von Schwester-Treu',
Und alle diese sel'gen Träume,
```

Ich würde gerne verhindern, dass somajo mir die trennt. 
Gibt es da eine Option in python?

`tokenizer = SoMaJo("de_CMC", split_camel_case=True)`

Vielen Dank.

**Comment by anonymous-poetrybot-386** [comment]
Ich habe übersehen, dass ich in meinem falschen Account bin, der eigentlich anonym bleiben sollte ... aber ich kann das issue nicht mehr löschen ...

**Comment by anonymous-poetrybot-386** [comment]
Ich sehe gerade, das ist gar nicht immer der Fall, aber doch schon ab und an. 

Auf die schnelle habe ich diese beiden Beispiele gefunden:

```
Durch's Haselholz in's Thal hinab,
['Durch', "'", 's', 'Haselholz', 'in', "'", 's', 'Thal', 'hinab', ',']
Von Mutter-Lieb', von Schwester-Treu',
['Von', 'Mutter-Lieb', "'", ',', 'von', 'Schwester-Treu', "'", ',']
```

Die hier sehen gut aus:

```
Und treiben's in dem Saale,
['Und', "treiben's", 'in', 'dem', 'Saale', ',']
Acht Kegel hinter'm Brett herauf,
['Acht', 'Kegel', "hinter'm", 'Brett', 'herauf', ',']

Schrei'n: Hagel und kein Ende!
["Schrei'n", ':', 'Hagel', 'und', 'kein', 'Ende', '!']
Spazieren auf dem Wiesenplan
['Spazieren', 'auf', 'dem', 'Wiesenplan']
Am Ende säh' ich selber mich,
['Am', 'Ende', "säh'", 'ich', 'selber', 'mich', ',']


```

**Comment by tsproisl** [comment]
Danke für die Fehlermeldung! Apostrophe innerhalb eines Wortes sollten eigentlich nicht abgetrennt werden. In den Beispielen, in denen das trotzdem passiert, hält der Tokenizer sie für einfache Anführungszeichen (passiert nur, wenn es zwei sind: ein „öffnendes“ und ein „schließendes“). Ich habe die Erkennung von Anführungszeichen jetzt etwas zurückhaltener gestaltet, so dass Apostrophzeichen in der Mitte eines Wortes nicht mehr für Anführungszeichen gehalten werden können.

**Comment by anonymous-poetrybot-386** [comment]
Ah super, danke!

Ich verstehe. Es wird dann getrennt, wenn zwei Anführungszeichen im Satz vorkommen.

Soll ich dann einfach das pip updaten oder die github version klonen?

**Comment by tsproisl** [comment]
> Soll ich dann einfach das pip updaten oder die github version klonen?

Genau, in Version 2.1.1 ist das geändert.
