### ISSUE TITLE
publish on conda-forge

### ISSUE THREAD

**Issue by iulusoy** [tsproisl/SoMaJo#22]
Hi, looks like you created a great package! I have built a [tool](https://github.com/ssciwr/argumentation-management) that utilizes SoMaJo, amongst others, and would like to make it available on conda-forge in addition to pypi. 
Since SoMaJo is not yet available on conda-forge, or other conda channels, I wanted to ask if you would like to [add it](https://conda-forge.org/docs/maintainer/adding_pkgs.html), otherwise I will create a recipe and do so (the release will not be affiliated with a specific user).
Until then I can not add [my package to conda-forge](https://github.com/conda/conda-build/issues/548).

**Comment by tsproisl** [comment]
Hi, sorry for the delayed response. Feel free to create a recipe for SoMaJo! I guess the best path would be to base the recipe on the PyPI releases.

**Comment by iulusoy** [comment]
Great, I will do so!
