### ISSUE TITLE
Document all possible values for `token_class`.

### ISSUE THREAD

**Issue by PhilipMay** [tsproisl/SoMaJo#24]
From user perspective it would be nice to know all possible values for `token_class`.

Here the doc only mentions some:

https://github.com/tsproisl/SoMaJo/blob/87e9cb00ff4f122e714643f55d9dc9b2bb5ab723/somajo/token.py#L20

Could you somehow provide a list of all values with a short description?

**Comment by PhilipMay** [comment]
Nice. Thanks!

**Comment by PhilipMay** [comment]
For reference: What I found is this:

```
{'regular': 1, 'symbol': 1, 'number': 1, 'ordinal': 1, 'date': 1, 'abbreviation': 1, 
'number_compound': 1, 'time': 1, 'email_address': 1, 'URL': 1, 'measurement': 1, 
'emoticon': 1, 'XML_entity': 1, 'hashtag': 1, 'amount': 1, 'XML_tag': 1, 'mention': 1, 
'action_word': 1, 'semester': 1}
```

**Comment by tsproisl** [comment]
For German texts, the "number_compound" token class was removed in version 2.2.4. It was still present for English texts (by accident) but was removed in 11977e030f5e700096685990a04cd701aba0f2ce. In 2.3.0 (released a few minutes ago), there should be no "number_compound" token class.
