### ISSUE TITLE
Getting Error where running the doc code

### ISSUE THREAD

**Issue by SAswinGiridhar** [tsproisl/SoMaJo#5]
![image](https://user-images.githubusercontent.com/11817160/56300813-3a9c9c00-6154-11e9-92cb-cf8414a667d8.png)

**Comment by tsproisl** [comment]
Unfortunately I'm not able to reproduce that error:
```
>>> from somajo import Tokenizer, SentenceSplitter
>>> tokenizer = Tokenizer(language="en")
>>> tokenizer.tokenize("Here's a simple example!:-)")
['That', "'s", 'a', 'great', 'example', '!', ':-)']
```
Which versions of SoMaJo and of the regex module are you using? For me everything works fine using SoMaJo 1.9.0 and regex 2.5.29.

**Comment by SAswinGiridhar** [comment]
Hi,
The versions are as follows:
regex==2017.11.9
SoMaJo==1.9.0
Python 3.6.3
Could you tell me which regex package did you use?
Thanks for taking your time to look into this issue.

**Comment by tsproisl** [comment]
I used version 2019.4.14 of the [regex](https://pypi.org/project/regex/) module (which self-reports as 2.5.29):
```
>>> regex.__version__
'2.5.29'
```
But even with version 2017.11.9 (self-reported as 2.4.132) everything works as expected.

Does [this minimal working example](https://github.com/tsproisl/SoMaJo/files/3107312/somajo_mwe.zip) work for you? What does it output (including complete stack trace, if any)? For me it looks like this:
```
regex: 2.4.132
somajo: 1.9.0
python: 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
default encoding: utf-8
['Here', "'s", 'a', 'simple', 'example', '!', ':-)']
```
