### ISSUE TITLE
crashes machine when used with multiprocessing

### ISSUE THREAD

**Issue by MiniXC** [tsproisl/SoMaJo#8]
I have tried using the tokenizer and sentence splitter with multiprocessing and ``mp.Pool``, which crashes my PC. I have tried using fewer cores but get the same outcome. This does not seem to be a memory leak, because RAM usage remains consistent.

Is there any obvious reason SoMaJo would fail when used with multiprocessing?

**Comment by bminixhofer** [comment]
I'm not a developer of SoMaJo but make sure to run multiprocessing in a Python interpreter, not IPython. Multiprocessing is known to [have some problems](https://stackoverflow.com/questions/23641475/multiprocessing-working-in-python-but-not-in-ipython/23641560#23641560) in IPython.

**Comment by tsproisl** [comment]
Does the answer by @bminixhofer settle the issue? If not, could you please provide a code example that reproduces the behavior?

**Comment by MiniXC** [comment]
This has to be a problem with my setup because the same happens with other libraries e.g. fastai - closing his because I think it is unlikely to be an issue with SoMaJo after all.
