### ISSUE TITLE
German text to sentence segmentation

### ISSUE THREAD

**Issue by Tortoise17** [tsproisl/SoMaJo#9]
I have German plain text without any stop or punctuation. How can i make sentence segmentation and  sentence stop with this tool?

**Comment by tsproisl** [comment]
I fear you are out of luck: SoMaJo's sentence splitting is based on regular expressions that look for punctuation characters. You probably need something along the lines of the system described by Ruppenhofer and Rehbein (2019).

Josef Ruppenhofer and Ines Rehbein (2019): “Detecting the boundaries of sentence-like units in spoken German.” In: _Proceedings of the 15th Conference on Natural Language Processing (KONVENS 2019)_, 130–139. <https://corpora.linguistik.uni-erlangen.de/data/konvens/proceedings/papers/KONVENS2019_paper_32.pdf>.
